'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Aparelho

    '''<summary>
    '''pnlObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObservacao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDLinhaConta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDLinhaConta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservacaoObrigatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoObrigatoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvObservacao As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btCancela control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancela As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfdId_Aparelho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfdId_Aparelho As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRegistro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDescRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFinalidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFinalidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinalidade As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblIdentificacaoModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentificacaoModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIndentificacaoModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIndentificacaoModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btFechar_Registro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btFechar_Registro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAparelhoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAparelhoTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAparelhoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAparelhoTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvAparelhoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAparelhoTipo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblNumeroAparelho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroAparelho As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumeroAparelho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroAparelho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvNumeroAparelho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumeroAparelho As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblLinhaSolicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLinhaSolicitacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLinhaSolicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinhaSolicitacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNumeroChamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroChamado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumeroChamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroChamado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvNumeroChamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumeroChamado As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblValorImobilizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValorImobilizado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboEstoqueAparelhoStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEstoqueAparelhoStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblEnderecoEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnderecoEntrega As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboEnderecoEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEnderecoEntrega As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btImprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btImprimir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNotaFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotaFiscal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboNotaFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNotaFiscal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvNotaFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNotaFiscal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblGestorEstoque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGestorEstoque As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboUsuarioEstoque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUsuarioEstoque As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvUsuarioEstoque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvUsuarioEstoque As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblConglomerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConglomerado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboConglomerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboConglomerado As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvConglomerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvConglomerado As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAtivoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtivoTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAtivoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAtivoTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvAtivoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAtivoTipo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAtivoModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtivoModelo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAtivoModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAtivoModelo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblNumeroAparelho2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroAparelho2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumeroAparelho2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroAparelho2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbAtivoAcessorios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAtivoAcessorios As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CkbCarregador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkbCarregador As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CkbCabo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkbCabo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CkbFone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkbFone As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CkbPelicula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkbPelicula As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CkbCapa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkbCapa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbSelecioneAcessorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSelecioneAcessorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumeroAtivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroAtivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescricaoLinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoLinha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblIdentificacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentificacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIdentificacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlValidador2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlValidador2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''vceNumeroAparelho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceNumeroAparelho As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceNotaFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceNotaFiscal As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceNumeroChamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceNumeroChamado As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceUsuarioEstoque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceUsuarioEstoque As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceAtivoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceAtivoTipo As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceAparelhoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceAparelhoTipo As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceConglomerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceConglomerado As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbBotao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBotao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btVoltar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btLimpar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSalvar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btDesativar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDesativar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btAbrir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAbrir As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As IControlIT.Principal
        Get
            Return CType(MyBase.Master, IControlIT.Principal)
        End Get
    End Property
End Class
