'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
'
Namespace WS_GUA_Chamado
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSChamadoSoap", [Namespace]:="WSChamado")>  _
    Partial Public Class WSChamado
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ChamadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AtivoChamadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AtivoRelacionamentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChamadoAuxiliarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IControlIT.My.MySettings.Default.IControlIT_localhost_WSChamado
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ChamadoCompleted As ChamadoCompletedEventHandler
        
        '''<remarks/>
        Public Event AtivoChamadoCompleted As AtivoChamadoCompletedEventHandler
        
        '''<remarks/>
        Public Event AtivoRelacionamentoCompleted As AtivoRelacionamentoCompletedEventHandler
        
        '''<remarks/>
        Public Event ChamadoAuxiliarCompleted As ChamadoAuxiliarCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/Chamado", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Chamado( _
                    ByVal pPConn_Banco As String,  _
                    ByVal pPakage As String,  _
                    ByVal pageNumber As Integer,  _
                    ByVal pageSize As Integer,  _
                    ByVal idChamado As Integer,  _
                    ByVal requestNumber As String,  _
                    ByVal workOrderNumber As String,  _
                    ByVal estado As String,  _
                    ByVal comentarios As String,  _
                    ByVal atribuidoPara As String,  _
                    ByVal tipoSolicitacao As String,  _
                    ByVal transactionID As String,  _
                    ByVal idConsumidor As Integer,  _
                    ByVal idAtivo As Integer,  _
                    ByVal idConglomerado As Integer,  _
                    ByVal userName As String,  _
                    ByVal userNumber As String,  _
                    ByVal designationProduct As String,  _
                    ByVal telecomProvider As String,  _
                    ByVal framingPlan As String,  _
                    ByVal migrationDevice As String,  _
                    ByVal servicePack As String,  _
                    ByVal newAreaCode As String,  _
                    ByVal newUserNumber As String,  _
                    ByVal newTelecomProvider As String,  _
                    ByVal countryDateForRoaming As String,  _
                    ByVal managerOrAdm As String,  _
                    ByVal viewProfile As String,  _
                    ByVal managerNumber As String,  _
                    ByVal additionalInformation As String,  _
                    ByVal name As String,  _
                    ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Chamado", New Object() {pPConn_Banco, pPakage, pageNumber, pageSize, idChamado, requestNumber, workOrderNumber, estado, comentarios, atribuidoPara, tipoSolicitacao, transactionID, idConsumidor, idAtivo, idConglomerado, userName, userNumber, designationProduct, telecomProvider, framingPlan, migrationDevice, servicePack, newAreaCode, newUserNumber, newTelecomProvider, countryDateForRoaming, managerOrAdm, viewProfile, managerNumber, additionalInformation, name, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChamadoAsync( _
                    ByVal pPConn_Banco As String,  _
                    ByVal pPakage As String,  _
                    ByVal pageNumber As Integer,  _
                    ByVal pageSize As Integer,  _
                    ByVal idChamado As Integer,  _
                    ByVal requestNumber As String,  _
                    ByVal workOrderNumber As String,  _
                    ByVal estado As String,  _
                    ByVal comentarios As String,  _
                    ByVal atribuidoPara As String,  _
                    ByVal tipoSolicitacao As String,  _
                    ByVal transactionID As String,  _
                    ByVal idConsumidor As Integer,  _
                    ByVal idAtivo As Integer,  _
                    ByVal idConglomerado As Integer,  _
                    ByVal userName As String,  _
                    ByVal userNumber As String,  _
                    ByVal designationProduct As String,  _
                    ByVal telecomProvider As String,  _
                    ByVal framingPlan As String,  _
                    ByVal migrationDevice As String,  _
                    ByVal servicePack As String,  _
                    ByVal newAreaCode As String,  _
                    ByVal newUserNumber As String,  _
                    ByVal newTelecomProvider As String,  _
                    ByVal countryDateForRoaming As String,  _
                    ByVal managerOrAdm As String,  _
                    ByVal viewProfile As String,  _
                    ByVal managerNumber As String,  _
                    ByVal additionalInformation As String,  _
                    ByVal name As String,  _
                    ByVal pRetorno As Boolean)
            Me.ChamadoAsync(pPConn_Banco, pPakage, pageNumber, pageSize, idChamado, requestNumber, workOrderNumber, estado, comentarios, atribuidoPara, tipoSolicitacao, transactionID, idConsumidor, idAtivo, idConglomerado, userName, userNumber, designationProduct, telecomProvider, framingPlan, migrationDevice, servicePack, newAreaCode, newUserNumber, newTelecomProvider, countryDateForRoaming, managerOrAdm, viewProfile, managerNumber, additionalInformation, name, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChamadoAsync( _
                    ByVal pPConn_Banco As String,  _
                    ByVal pPakage As String,  _
                    ByVal pageNumber As Integer,  _
                    ByVal pageSize As Integer,  _
                    ByVal idChamado As Integer,  _
                    ByVal requestNumber As String,  _
                    ByVal workOrderNumber As String,  _
                    ByVal estado As String,  _
                    ByVal comentarios As String,  _
                    ByVal atribuidoPara As String,  _
                    ByVal tipoSolicitacao As String,  _
                    ByVal transactionID As String,  _
                    ByVal idConsumidor As Integer,  _
                    ByVal idAtivo As Integer,  _
                    ByVal idConglomerado As Integer,  _
                    ByVal userName As String,  _
                    ByVal userNumber As String,  _
                    ByVal designationProduct As String,  _
                    ByVal telecomProvider As String,  _
                    ByVal framingPlan As String,  _
                    ByVal migrationDevice As String,  _
                    ByVal servicePack As String,  _
                    ByVal newAreaCode As String,  _
                    ByVal newUserNumber As String,  _
                    ByVal newTelecomProvider As String,  _
                    ByVal countryDateForRoaming As String,  _
                    ByVal managerOrAdm As String,  _
                    ByVal viewProfile As String,  _
                    ByVal managerNumber As String,  _
                    ByVal additionalInformation As String,  _
                    ByVal name As String,  _
                    ByVal pRetorno As Boolean,  _
                    ByVal userState As Object)
            If (Me.ChamadoOperationCompleted Is Nothing) Then
                Me.ChamadoOperationCompleted = AddressOf Me.OnChamadoOperationCompleted
            End If
            Me.InvokeAsync("Chamado", New Object() {pPConn_Banco, pPakage, pageNumber, pageSize, idChamado, requestNumber, workOrderNumber, estado, comentarios, atribuidoPara, tipoSolicitacao, transactionID, idConsumidor, idAtivo, idConglomerado, userName, userNumber, designationProduct, telecomProvider, framingPlan, migrationDevice, servicePack, newAreaCode, newUserNumber, newTelecomProvider, countryDateForRoaming, managerOrAdm, viewProfile, managerNumber, additionalInformation, name, pRetorno}, Me.ChamadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnChamadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChamadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChamadoCompleted(Me, New ChamadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/AtivoChamado", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AtivoChamado(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Chamado As Integer, ByVal pId_Ativo As Integer, ByVal pNr_Ativo As String, ByVal pNewNr_Ativo As String, ByVal pNewAreaCode As String, ByVal pId_Conglomerado As Integer, ByVal pPlano_Contrato As String, ByVal pComentarios As String, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("AtivoChamado", New Object() {pPConn_Banco, pPakage, pId_Chamado, pId_Ativo, pNr_Ativo, pNewNr_Ativo, pNewAreaCode, pId_Conglomerado, pPlano_Contrato, pComentarios, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AtivoChamadoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Chamado As Integer, ByVal pId_Ativo As Integer, ByVal pNr_Ativo As String, ByVal pNewNr_Ativo As String, ByVal pNewAreaCode As String, ByVal pId_Conglomerado As Integer, ByVal pPlano_Contrato As String, ByVal pComentarios As String, ByVal pRetorno As Boolean)
            Me.AtivoChamadoAsync(pPConn_Banco, pPakage, pId_Chamado, pId_Ativo, pNr_Ativo, pNewNr_Ativo, pNewAreaCode, pId_Conglomerado, pPlano_Contrato, pComentarios, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AtivoChamadoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Chamado As Integer, ByVal pId_Ativo As Integer, ByVal pNr_Ativo As String, ByVal pNewNr_Ativo As String, ByVal pNewAreaCode As String, ByVal pId_Conglomerado As Integer, ByVal pPlano_Contrato As String, ByVal pComentarios As String, ByVal pRetorno As Boolean, ByVal userState As Object)
            If (Me.AtivoChamadoOperationCompleted Is Nothing) Then
                Me.AtivoChamadoOperationCompleted = AddressOf Me.OnAtivoChamadoOperationCompleted
            End If
            Me.InvokeAsync("AtivoChamado", New Object() {pPConn_Banco, pPakage, pId_Chamado, pId_Ativo, pNr_Ativo, pNewNr_Ativo, pNewAreaCode, pId_Conglomerado, pPlano_Contrato, pComentarios, pRetorno}, Me.AtivoChamadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAtivoChamadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AtivoChamadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AtivoChamadoCompleted(Me, New AtivoChamadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/AtivoRelacionamento", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AtivoRelacionamento(ByVal pPConn_Banco As String, ByVal pId_Chamado As Integer, ByVal pId_Ativo As Integer, ByVal pUserNumber As Integer, ByVal pPakage As String, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("AtivoRelacionamento", New Object() {pPConn_Banco, pId_Chamado, pId_Ativo, pUserNumber, pPakage, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AtivoRelacionamentoAsync(ByVal pPConn_Banco As String, ByVal pId_Chamado As Integer, ByVal pId_Ativo As Integer, ByVal pUserNumber As Integer, ByVal pPakage As String, ByVal pRetorno As Boolean)
            Me.AtivoRelacionamentoAsync(pPConn_Banco, pId_Chamado, pId_Ativo, pUserNumber, pPakage, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AtivoRelacionamentoAsync(ByVal pPConn_Banco As String, ByVal pId_Chamado As Integer, ByVal pId_Ativo As Integer, ByVal pUserNumber As Integer, ByVal pPakage As String, ByVal pRetorno As Boolean, ByVal userState As Object)
            If (Me.AtivoRelacionamentoOperationCompleted Is Nothing) Then
                Me.AtivoRelacionamentoOperationCompleted = AddressOf Me.OnAtivoRelacionamentoOperationCompleted
            End If
            Me.InvokeAsync("AtivoRelacionamento", New Object() {pPConn_Banco, pId_Chamado, pId_Ativo, pUserNumber, pPakage, pRetorno}, Me.AtivoRelacionamentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAtivoRelacionamentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AtivoRelacionamentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AtivoRelacionamentoCompleted(Me, New AtivoRelacionamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/ChamadoAuxiliar", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChamadoAuxiliar(ByVal pPConn_Banco As String, ByVal pAcao As String, ByVal id_Conglomerado As Integer, ByVal id_Ativo As Integer, ByVal pEmailDestino As String, ByVal pEmailCopia As String, ByVal id_Mail_Sender As Integer, ByVal pTextoAdicional As String, ByVal pAssuntoEmail As String, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ChamadoAuxiliar", New Object() {pPConn_Banco, pAcao, id_Conglomerado, id_Ativo, pEmailDestino, pEmailCopia, id_Mail_Sender, pTextoAdicional, pAssuntoEmail, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChamadoAuxiliarAsync(ByVal pPConn_Banco As String, ByVal pAcao As String, ByVal id_Conglomerado As Integer, ByVal id_Ativo As Integer, ByVal pEmailDestino As String, ByVal pEmailCopia As String, ByVal id_Mail_Sender As Integer, ByVal pTextoAdicional As String, ByVal pAssuntoEmail As String, ByVal pRetorno As Boolean)
            Me.ChamadoAuxiliarAsync(pPConn_Banco, pAcao, id_Conglomerado, id_Ativo, pEmailDestino, pEmailCopia, id_Mail_Sender, pTextoAdicional, pAssuntoEmail, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChamadoAuxiliarAsync(ByVal pPConn_Banco As String, ByVal pAcao As String, ByVal id_Conglomerado As Integer, ByVal id_Ativo As Integer, ByVal pEmailDestino As String, ByVal pEmailCopia As String, ByVal id_Mail_Sender As Integer, ByVal pTextoAdicional As String, ByVal pAssuntoEmail As String, ByVal pRetorno As Boolean, ByVal userState As Object)
            If (Me.ChamadoAuxiliarOperationCompleted Is Nothing) Then
                Me.ChamadoAuxiliarOperationCompleted = AddressOf Me.OnChamadoAuxiliarOperationCompleted
            End If
            Me.InvokeAsync("ChamadoAuxiliar", New Object() {pPConn_Banco, pAcao, id_Conglomerado, id_Ativo, pEmailDestino, pEmailCopia, id_Mail_Sender, pTextoAdicional, pAssuntoEmail, pRetorno}, Me.ChamadoAuxiliarOperationCompleted, userState)
        End Sub
        
        Private Sub OnChamadoAuxiliarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChamadoAuxiliarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChamadoAuxiliarCompleted(Me, New ChamadoAuxiliarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ChamadoCompletedEventHandler(ByVal sender As Object, ByVal e As ChamadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChamadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AtivoChamadoCompletedEventHandler(ByVal sender As Object, ByVal e As AtivoChamadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AtivoChamadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AtivoRelacionamentoCompletedEventHandler(ByVal sender As Object, ByVal e As AtivoRelacionamentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AtivoRelacionamentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ChamadoAuxiliarCompletedEventHandler(ByVal sender As Object, ByVal e As ChamadoAuxiliarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChamadoAuxiliarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
