'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
'
Namespace WS_GUA_Chamado
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSChamadoSoap", [Namespace]:="WSChamado")>  _
    Partial Public Class WSChamado
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TodosChamadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChamadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Ativo_ChamadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Ativo_RelacionamentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IControlIT.My.MySettings.Default.IControlIT_localhost_WSChamado
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TodosChamadosCompleted As TodosChamadosCompletedEventHandler
        
        '''<remarks/>
        Public Event ChamadoCompleted As ChamadoCompletedEventHandler
        
        '''<remarks/>
        Public Event Ativo_ChamadoCompleted As Ativo_ChamadoCompletedEventHandler
        
        '''<remarks/>
        Public Event Ativo_RelacionamentoCompleted As Ativo_RelacionamentoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/TodosChamados", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TodosChamados(ByVal pPConn_Banco As String, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TodosChamados", New Object() {pPConn_Banco, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TodosChamadosAsync(ByVal pPConn_Banco As String, ByVal pRetorno As Boolean)
            Me.TodosChamadosAsync(pPConn_Banco, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TodosChamadosAsync(ByVal pPConn_Banco As String, ByVal pRetorno As Boolean, ByVal userState As Object)
            If (Me.TodosChamadosOperationCompleted Is Nothing) Then
                Me.TodosChamadosOperationCompleted = AddressOf Me.OnTodosChamadosOperationCompleted
            End If
            Me.InvokeAsync("TodosChamados", New Object() {pPConn_Banco, pRetorno}, Me.TodosChamadosOperationCompleted, userState)
        End Sub
        
        Private Sub OnTodosChamadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.TodosChamadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TodosChamadosCompleted(Me, New TodosChamadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/Chamado", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Chamado(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Chamado As Integer, ByVal pCorrelationId As String, ByVal pNumero_Solicitacao As String, ByVal pEstado As String, ByVal pComentarios As String, ByVal pAtribuido_Para As String, ByVal pTipo_Solicitacao As String, ByVal pTransactionID As String, ByVal pId_Consumidor As Integer, ByVal pId_Ativo As Integer, ByVal pId_Conglomerado As Integer, ByVal pId_Plano As Integer, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Chamado", New Object() {pPConn_Banco, pPakage, pId_Chamado, pCorrelationId, pNumero_Solicitacao, pEstado, pComentarios, pAtribuido_Para, pTipo_Solicitacao, pTransactionID, pId_Consumidor, pId_Ativo, pId_Conglomerado, pId_Plano, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChamadoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Chamado As Integer, ByVal pCorrelationId As String, ByVal pNumero_Solicitacao As String, ByVal pEstado As String, ByVal pComentarios As String, ByVal pAtribuido_Para As String, ByVal pTipo_Solicitacao As String, ByVal pTransactionID As String, ByVal pId_Consumidor As Integer, ByVal pId_Ativo As Integer, ByVal pId_Conglomerado As Integer, ByVal pId_Plano As Integer, ByVal pRetorno As Boolean)
            Me.ChamadoAsync(pPConn_Banco, pPakage, pId_Chamado, pCorrelationId, pNumero_Solicitacao, pEstado, pComentarios, pAtribuido_Para, pTipo_Solicitacao, pTransactionID, pId_Consumidor, pId_Ativo, pId_Conglomerado, pId_Plano, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChamadoAsync( _
                    ByVal pPConn_Banco As String,  _
                    ByVal pPakage As String,  _
                    ByVal pId_Chamado As Integer,  _
                    ByVal pCorrelationId As String,  _
                    ByVal pNumero_Solicitacao As String,  _
                    ByVal pEstado As String,  _
                    ByVal pComentarios As String,  _
                    ByVal pAtribuido_Para As String,  _
                    ByVal pTipo_Solicitacao As String,  _
                    ByVal pTransactionID As String,  _
                    ByVal pId_Consumidor As Integer,  _
                    ByVal pId_Ativo As Integer,  _
                    ByVal pId_Conglomerado As Integer,  _
                    ByVal pId_Plano As Integer,  _
                    ByVal pRetorno As Boolean,  _
                    ByVal userState As Object)
            If (Me.ChamadoOperationCompleted Is Nothing) Then
                Me.ChamadoOperationCompleted = AddressOf Me.OnChamadoOperationCompleted
            End If
            Me.InvokeAsync("Chamado", New Object() {pPConn_Banco, pPakage, pId_Chamado, pCorrelationId, pNumero_Solicitacao, pEstado, pComentarios, pAtribuido_Para, pTipo_Solicitacao, pTransactionID, pId_Consumidor, pId_Ativo, pId_Conglomerado, pId_Plano, pRetorno}, Me.ChamadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnChamadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChamadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChamadoCompleted(Me, New ChamadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/Ativo_Chamado", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ativo_Chamado(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Ativo As Integer, ByVal pId_Ativo_Status As Integer, ByVal pNr_Ativo As String, ByVal pNewNr_Ativo As String, ByVal pNewAreaCode As String, ByVal pId_Conglomerado As Integer, ByVal pPlano_Contrato As String, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Ativo_Chamado", New Object() {pPConn_Banco, pPakage, pId_Ativo, pId_Ativo_Status, pNr_Ativo, pNewNr_Ativo, pNewAreaCode, pId_Conglomerado, pPlano_Contrato, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Ativo_ChamadoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Ativo As Integer, ByVal pId_Ativo_Status As Integer, ByVal pNr_Ativo As String, ByVal pNewNr_Ativo As String, ByVal pNewAreaCode As String, ByVal pId_Conglomerado As Integer, ByVal pPlano_Contrato As String, ByVal pRetorno As Boolean)
            Me.Ativo_ChamadoAsync(pPConn_Banco, pPakage, pId_Ativo, pId_Ativo_Status, pNr_Ativo, pNewNr_Ativo, pNewAreaCode, pId_Conglomerado, pPlano_Contrato, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Ativo_ChamadoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Ativo As Integer, ByVal pId_Ativo_Status As Integer, ByVal pNr_Ativo As String, ByVal pNewNr_Ativo As String, ByVal pNewAreaCode As String, ByVal pId_Conglomerado As Integer, ByVal pPlano_Contrato As String, ByVal pRetorno As Boolean, ByVal userState As Object)
            If (Me.Ativo_ChamadoOperationCompleted Is Nothing) Then
                Me.Ativo_ChamadoOperationCompleted = AddressOf Me.OnAtivo_ChamadoOperationCompleted
            End If
            Me.InvokeAsync("Ativo_Chamado", New Object() {pPConn_Banco, pPakage, pId_Ativo, pId_Ativo_Status, pNr_Ativo, pNewNr_Ativo, pNewAreaCode, pId_Conglomerado, pPlano_Contrato, pRetorno}, Me.Ativo_ChamadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAtivo_ChamadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Ativo_ChamadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Ativo_ChamadoCompleted(Me, New Ativo_ChamadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("WSChamado/Ativo_Relacionamento", RequestNamespace:="WSChamado", ResponseNamespace:="WSChamado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ativo_Relacionamento(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Ativo As Integer, ByVal pId_Consumidor As Integer, ByVal pDt_Hr_Desativacao As Date, ByVal pRetorno As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Ativo_Relacionamento", New Object() {pPConn_Banco, pPakage, pId_Ativo, pId_Consumidor, pDt_Hr_Desativacao, pRetorno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Ativo_RelacionamentoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Ativo As Integer, ByVal pId_Consumidor As Integer, ByVal pDt_Hr_Desativacao As Date, ByVal pRetorno As Boolean)
            Me.Ativo_RelacionamentoAsync(pPConn_Banco, pPakage, pId_Ativo, pId_Consumidor, pDt_Hr_Desativacao, pRetorno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Ativo_RelacionamentoAsync(ByVal pPConn_Banco As String, ByVal pPakage As String, ByVal pId_Ativo As Integer, ByVal pId_Consumidor As Integer, ByVal pDt_Hr_Desativacao As Date, ByVal pRetorno As Boolean, ByVal userState As Object)
            If (Me.Ativo_RelacionamentoOperationCompleted Is Nothing) Then
                Me.Ativo_RelacionamentoOperationCompleted = AddressOf Me.OnAtivo_RelacionamentoOperationCompleted
            End If
            Me.InvokeAsync("Ativo_Relacionamento", New Object() {pPConn_Banco, pPakage, pId_Ativo, pId_Consumidor, pDt_Hr_Desativacao, pRetorno}, Me.Ativo_RelacionamentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAtivo_RelacionamentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Ativo_RelacionamentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Ativo_RelacionamentoCompleted(Me, New Ativo_RelacionamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub TodosChamadosCompletedEventHandler(ByVal sender As Object, ByVal e As TodosChamadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TodosChamadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ChamadoCompletedEventHandler(ByVal sender As Object, ByVal e As ChamadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChamadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Ativo_ChamadoCompletedEventHandler(ByVal sender As Object, ByVal e As Ativo_ChamadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Ativo_ChamadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Ativo_RelacionamentoCompletedEventHandler(ByVal sender As Object, ByVal e As Ativo_RelacionamentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Ativo_RelacionamentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
